# Generated by Django 3.2 on 2021-04-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_details',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
    ]
